#!/bin/bash

last_touched_mins=1
input_dir=/input
output_dir=/output

trap "rm -f /tmp/handbrake-cli.lock" SIGINT SIGTERM
if [ -e /tmp/handbrake-cli.lock ]; then
  echo "handbrake-cli is running already."
  exit 1
else
  find $input_dir -type f -mmin +$last_touched_mins -print0 | xargs -0 -i /scripts/handbrake {}
  rm -f /tmp/handbrake-cli.lock
  exit 0
fi
